server:
  port: 8888

spring:
  application:
    name: gateway-service
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
zuul:
  routes:
    department-server:
      serviceId: department-server
      path: /departments/**
      stripPrefix: false
    employee-server:
      serviceId: employee-server
      path: /employees/**
      stripPrefix: false
  ribbon:
    eager-load:
      enabled: true

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000